# Generated by Django 3.0.5 on 2020-05-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20200506_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufactureDate',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacture Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='purchaseCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Supplier'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warrantyExpiration',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Expiration Date'),
        ),
    ]
