# Generated by Django 3.0.5 on 2020-05-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_asset_ownerdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='ownerDepartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ownerDepartment', to='maintenance.Department'),
            preserve_default=False,
        ),
    ]
