# Generated by Django 3.0.5 on 2020-04-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_asset_department_manufacturer_model_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Model'),
            preserve_default=False,
        ),
    ]
