# Generated by Django 3.0.5 on 2020-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20200506_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
