# Generated by Django 3.0.5 on 2020-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20200519_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(max_length=100, verbose_name='Account Number'),
        ),
    ]
