# Generated by Django 3.0.5 on 2020-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20200506_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('instore', 'In Store'), ('inuse', 'In User'), ('inrepair', 'In Repair'), ('disposed', 'disposed')], default='instore', max_length=30),
        ),
    ]
