# Generated by Django 3.0.5 on 2020-05-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20200513_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
