# Generated by Django 3.0.5 on 2020-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('instore', 'In Store'), ('inuse', 'In Use'), ('inrepair', 'In Repair'), ('disposed', 'Disposed')], default='instore', max_length=30),
        ),
    ]
