# Generated by Django 3.0.5 on 2020-05-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_consumable_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('purchaseOrderId', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.OrganizationUsers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
