# Generated by Django 3.0.5 on 2020-05-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Department'),
            preserve_default=False,
        ),
    ]
