# Generated by Django 3.0.5 on 2020-05-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20200506_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Department'),
        ),
    ]
