# Generated by Django 3.0.5 on 2020-05-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_consumableledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableledger',
            name='consumable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Consumable'),
            preserve_default=False,
        ),
    ]
