# Generated by Django 3.0.5 on 2020-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20200519_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
