# Generated by Django 3.0.5 on 2020-05-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20200513_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='tag',
        ),
    ]
