# Generated by Django 3.0.5 on 2020-05-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20200520_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.PurchaseOrder', verbose_name='Purchase Order'),
        ),
    ]
