# Generated by Django 3.0.5 on 2020-06-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20200527_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expirationDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
