# Generated by Django 3.0.5 on 2020-06-10 04:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20200610_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
