# Generated by Django 3.0.5 on 2020-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationusers',
            name='userId',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('instore', 'In Store'), ('inuse', 'In Use'), ('onorder', 'On Order'), ('inrepair', 'In Repair'), ('discontinued', 'Discontinued'), ('disposed', 'Disposed')], default='instore', max_length=30),
        ),
    ]
