# Generated by Django 3.0.5 on 2020-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
