# Generated by Django 3.0.5 on 2020-05-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20200513_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchaseCost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Tag/Barcode'),
        ),
        migrations.AlterField(
            model_name='consumableledger',
            name='action',
            field=models.CharField(choices=[('in', 'Receive'), ('out', 'Checkout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationusers',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='organizationusers',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='organizationusers',
            name='userId',
            field=models.CharField(max_length=100, verbose_name='User ID'),
        ),
    ]
