# Generated by Django 3.0.5 on 2020-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
    ]
