# Generated by Django 3.0.5 on 2020-05-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('taxRate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discount', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.PurchaseOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
