# Generated by Django 3.0.5 on 2020-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_auto_20200516_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default='ttt', max_length=100, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
