# Generated by Django 3.0.5 on 2020-05-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_customuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID'),
        ),
    ]
