# Generated by Django 3.0.5 on 2020-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_auto_20200516_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default='N/A', max_length=100, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
