# Generated by Django 3.0.5 on 2020-05-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_auto_20200518_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Address'),
        ),
    ]
