# Generated by Django 3.0.5 on 2020-05-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrow',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
