# Generated by Django 3.0.5 on 2020-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_auto_20200518_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaseOrderNumber',
            field=models.CharField(default='', max_length=100, verbose_name='PO Number'),
            preserve_default=False,
        ),
    ]
