# Generated by Django 3.0.5 on 2020-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_auto_20200518_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderrow',
            name='recevied',
            field=models.IntegerField(default=0),
        ),
    ]
