# Generated by Django 3.0.5 on 2020-05-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_purchaseorderrow_recevied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderrow',
            old_name='recevied',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='consumableledger',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.PurchaseOrder', verbose_name='Purchase Order'),
        ),
    ]
