# Generated by Django 3.0.5 on 2020-05-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0031_auto_20200518_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderrow',
            name='itemType',
            field=models.CharField(default='asset', max_length=20),
            preserve_default=False,
        ),
    ]
