# Generated by Django 3.0.5 on 2020-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_purchaseorderrow_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='itemType',
            field=models.CharField(choices=[('asset', 'Asset'), ('component', 'Component'), ('consumables', 'Consumables')], max_length=20, verbose_name='Type'),
        ),
    ]
