# Generated by Django 3.0.5 on 2020-05-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0033_auto_20200518_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumableledger',
            name='purchaseOrderId',
        ),
        migrations.AddField(
            model_name='asset',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.PurchaseOrder', verbose_name='Linked Purchase Order'),
        ),
        migrations.AddField(
            model_name='component',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.PurchaseOrder', verbose_name='Linked Purchase Order'),
        ),
        migrations.AddField(
            model_name='consumableledger',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.PurchaseOrder', verbose_name='Linked Purchase Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='itemType',
            field=models.CharField(choices=[('asset', 'Asset'), ('component', 'Component'), ('consumables', 'Consumables'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
