# Generated by Django 3.0.5 on 2020-05-19 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_auto_20200518_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumable',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumableledger',
            name='externalPurchaseOrder',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='External Purchase Order #'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('open', 'Open'), ('onhold', 'On Hold'), ('inrepair', 'In Repair'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=30)),
                ('type', models.CharField(choices=[('repair', 'Repair'), ('install', 'New Install'), ('preventive', 'Preventive Maintenance'), ('inspection', 'Inspection')], default='repair', max_length=30)),
                ('requiredByDate', models.DateField(verbose_name='Required By Date')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignedTo', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestedBy', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
