# Generated by Django 3.0.5 on 2020-05-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0035_auto_20200519_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Account'),
            preserve_default=False,
        ),
    ]
